inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 45