inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 45

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
    - have_

Metrics/ClassLength:
  Enabled: false