# frozen_string_literal: true

require_relative 'models/base'
require_relative 'models/employee'
require_relative 'models/equity_grant'
require_relative 'models/salary'
require_relative 'models/training'
require_relative 'models/variable_payment'
require_relative 'models/time_off'
require_relative 'models/company_list'
require_relative 'models/company_field'
require_relative 'models/onboarding_wizard'
require_relative 'models/work_history'
require_relative 'models/lifecycle_history'
require_relative 'models/employment_history'
